
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/mysql-data:/var/lib/mysql
      - ./api/tmp/dockerdir:/etc/mysql/conf.d/
  api:
    build: 
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  front: 
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front/src:/app/src
    ports:
      - "3001:3000"
volumes:
  mysql-data:
    driver: local